// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6kEywWrH6yBtBe7mVpYKlDzlh8o6R_ZM',
    appId: '1:469057146515:web:5222d822415cc9370ec766',
    messagingSenderId: '469057146515',
    projectId: 'mindease-medicalchatbot',
    authDomain: 'mindease-medicalchatbot.firebaseapp.com',
    storageBucket: 'mindease-medicalchatbot.firebasestorage.app',
    measurementId: 'G-VCRZJB86G6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVaRIgRQbdbPgKRqq5xbX6ffe14ykPgsU',
    appId: '1:469057146515:android:c9b88c9097208f020ec766',
    messagingSenderId: '469057146515',
    projectId: 'mindease-medicalchatbot',
    storageBucket: 'mindease-medicalchatbot.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6kEywWrH6yBtBe7mVpYKlDzlh8o6R_ZM',
    appId: '1:469057146515:web:5222d822415cc9370ec766',
    messagingSenderId: '469057146515',
    projectId: 'mindease-medicalchatbot',
    authDomain: 'mindease-medicalchatbot.firebaseapp.com',
    storageBucket: 'mindease-medicalchatbot.firebasestorage.app',
    measurementId: 'G-VCRZJB86G6',
  );
}
